### PR TITLE
Changed printing behavior and cleaned up stopping function

### PR DESCRIPTION
**Pull request by Sparpet**
Now -v is needed for printing debugging information except for j,i,p,S options which print by default. 
Also implemented (and cleaned up from previous PR) stopping function by checking the prescence of a shared memory object between each moving/waiting loop.

### CODE REVIEW

**Comment by Sparpet** [comment]
At this point I think we have parity with original motors app and now is compatible with frigate for auto tracking.

**Comment by gtxaspec** [comment]
@Sparpet just following up, is this ready to be merged into production? thanks!

**Comment by Sparpet** [comment]
Yes, as far as I tested no further issues, should be in paroty with whta we currently have

**Comment by gtxaspec** [comment]
@Sparpet just double checking, did this PR need any changes to the motor driver itself?

**Comment by gtxaspec** [comment]
OK i tested, works well. i'll merge it in a bit

 some notes. 
we should print an error if the daemon is already running, displaying the current PID, to let the user know
running motors by itself should display the help message

**Pull request merged**
